// article actions
export const GET_ARTICLES = "GET_ARTICLES";
export const GET_ARTICLES_LOAD = "GET_ARTICLES_LOAD";
export const GET_ARTICLES_SUCCES = "GET_ARTICLES_SUCCES";
export const GET_ARTICLES_FAIL = "GET_ARTICLES_FAIL";
// comments actions
export const GET_COMMENTS = "GET_COMMENTS";
export const GET_COMMENTS_LOAD = "GET_COMMENTS_LOAD";
export const GET_COMMENTS_SUCCES = "GET_COMMENTS_SUCCES";
export const GET_COMMENTS_FAIL = "GET_COMMENTS_FAIL";

export const LIKE_COMMENT = "LIKE_COMMENT";
export const OPEN_COMMENT_REPLIES = "OPEN_COMMENT_REPLIES";
export const CLOSE_COMMENT_REPLIES = "CLOSE_COMMENT_REPLIES";